from enum import Enum

class RECORD_TYPES(Enum):
  HANDSHAKE = "16"
  CHANGE_CIPHER_SPEC = "14"
  APPLICATION_DATA = "17"
  ALERT = "15"

class HANDSHAKE_MESSAGE_TYPES(Enum):
  CLIENT_HELLO = "01"
  SERVER_HELLO = "02"
  CERTIFICATE = "0b"
  SERVER_KEY_EXCHANGE = "0c"
  SERVER_HELLO_DONE = "0e"
  CLIENT_KEY_EXCHANGE = "10"
  FINISHED = "14"

class COMPRESSION_METHODS(Enum):
  NO_COMPRESSION = "00"

